import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>수빈공주의 웹사이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>반가워 칭구들 나야 나~~</h1>
        <p>수빈이 세상에 오신 걸 환영합니다!</p>
      </main>
    </div>
  )
}
